//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignerLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesignerLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Caption_Warning {
            get {
                return ResourceManager.GetString("Caption_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring to back.
        /// </summary>
        internal static string ContextMenu_BringToBack {
            get {
                return ResourceManager.GetString("ContextMenu_BringToBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring to front.
        /// </summary>
        internal static string ContextMenu_BringToFront {
            get {
                return ResourceManager.GetString("ContextMenu_BringToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ContextMenu_Delete {
            get {
                return ResourceManager.GetString("ContextMenu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image file location!.
        /// </summary>
        internal static string Error_InvalidFileLocation {
            get {
                return ResourceManager.GetString("Error_InvalidFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid layer name!.
        /// </summary>
        internal static string Error_InvalidLayerName {
            get {
                return ResourceManager.GetString("Error_InvalidLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Description&gt;.
        /// </summary>
        internal static string LayerDescription {
            get {
                return ResourceManager.GetString("LayerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string LineWidth_Medium {
            get {
                return ResourceManager.GetString("LineWidth_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thick.
        /// </summary>
        internal static string LineWidth_Thick {
            get {
                return ResourceManager.GetString("LineWidth_Thick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thin.
        /// </summary>
        internal static string LineWidth_Thin {
            get {
                return ResourceManager.GetString("LineWidth_Thin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc.
        /// </summary>
        internal static string Tool_Arc {
            get {
                return ResourceManager.GetString("Tool_Arc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string Tool_Barcode {
            get {
                return ResourceManager.GetString("Tool_Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipse.
        /// </summary>
        internal static string Tool_Ellipse {
            get {
                return ResourceManager.GetString("Tool_Ellipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Tool_Image {
            get {
                return ResourceManager.GetString("Tool_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Tool_Line {
            get {
                return ResourceManager.GetString("Tool_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointer.
        /// </summary>
        internal static string Tool_Pointer {
            get {
                return ResourceManager.GetString("Tool_Pointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon.
        /// </summary>
        internal static string Tool_Polygon {
            get {
                return ResourceManager.GetString("Tool_Polygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        internal static string Tool_Rectangle {
            get {
                return ResourceManager.GetString("Tool_Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Tool_Text {
            get {
                return ResourceManager.GetString("Tool_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this tool?.
        /// </summary>
        internal static string Warning_Delete {
            get {
                return ResourceManager.GetString("Warning_Delete", resourceCulture);
            }
        }
    }
}
